In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("cars.csv")
df.sample(5)

        brand  km_driven    fuel         owner  selling_price
1900   Toyota     185000  Diesel  Second Owner         300000
3907   Datsun      35000  Petrol   Third Owner         260000
7118     Tata     120000  Diesel  Second Owner         350000
1292     Ford      90000  Diesel   First Owner         600000
205   Hyundai      70000  Petrol   First Owner         375000

In [3]:
# Get Dummies
pd.get_dummies(df, columns=["fuel", "owner"], drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

# Using SKLEARN

In [4]:
df.sample(5)

         brand  km_driven    fuel         owner  selling_price
2168  Mahindra      40000  Diesel  Second Owner         320000
4215    Jaguar       9000  Diesel   First Owner        2711000
508       Tata     201850  Diesel  Second Owner          88000
921    Renault      10000  Petrol   First Owner         340000
7002   Hyundai      80000  Petrol  Second Owner         110000

In [5]:
df.shape

(8128, 5)

In [6]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split

In [7]:
# train-test-split
X_train, X_test, y_train, y_test = train_test_split(df[["brand", "km_driven", "fuel", "owner"]], df["selling_price"], train_size=0.8, random_state=0)

In [8]:
ohe = OneHotEncoder()

In [9]:
ohe.fit_transform(X_train[["fuel", "owner"]])

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 13004 stored elements and shape (6502, 9)>