In [1]:
# Step 1: Import the necessary libraries
import numpy as np
import pandas as pd

In [2]:
# Step 2 and 3: Import the dataset from this address, assign it to a variable called chipo
chipo = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv", sep="\t")
chipo.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

In [3]:
# Change the data type of item_price to float
dollarizer = lambda x: float(x[1:])
chipo["item_price"] = chipo["item_price"].apply(dollarizer)

In [9]:
# Step 4: How many products cost more than $10.00?
chipo.loc[chipo["item_price"] > 10.00].shape[0]

1130

In [10]:
# Step 6: Sort by the name of the item
chipo.sort_values(by=["item_name"])

,order_id,quantity,item_name,choice_description,item_price
3389,1360,2,6 Pack Soft Drink,[Diet Coke],12.98
341,148,1,6 Pack Soft Drink,[Diet Coke],6.49
1849,749,1,6 Pack Soft Drink,[Coke],6.49
1860,754,1,6 Pack Soft Drink,[Diet Coke],6.49
2713,1076,1,6 Pack Soft Drink,[Coke],6.49
...,...,...,...,...,...
2384,948,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75
781,322,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Black Beans, Cheese, Sou...",8.75
2851,1132,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",8.49
1699,688,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
1395,567,1,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",8.49

In [12]:
# Step 7: What was the quantity of the most expensive item ordered?
chipo.loc[chipo["item_price"] == 44.25, "quantity"]

3598    15
Name: quantity, dtype: int64

In [15]:
# Step 8: How many times was a Veggie Salad Bowl ordered - Veggie Salad Bowl
chipo[chipo["item_name"] == "Veggie Salad Bowl"]["quantity"].sum()

np.int64(18)

In [25]:
# Step 9: How many times did someone order more than one Canned Soda? - Canned Soda
chipo[(chipo["item_name"] == "Canned Soda") & (chipo["quantity"] > 1)].shape[0]

20