In [2]:
# Step 1: Import the libraries
import pandas as pd

In [3]:
# Step 2 and 3: Import the data and assign it to a variable called drinks
drinks = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/drinks.csv")
drinks.head()

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,AS
1,Albania,89,132,54,4.9,EU
2,Algeria,25,0,14,0.7,AF
3,Andorra,245,138,312,12.4,EU
4,Angola,217,57,45,5.9,AF

In [4]:
drinks.shape

(193, 6)

In [8]:
# Step 4: Which continent drinks more beer on average?
round(drinks.groupby("continent")["beer_servings"].mean().sort_values(ascending=False).head(1))

continent
EU    194.0
Name: beer_servings, dtype: float64

In [9]:
# Step 5: For each continent print the statistics for wine consumption
drinks.groupby("continent")["wine_servings"].describe()

           count        mean        std  min   25%    50%     75%    max
continent
AF          53.0   16.264151  38.846419  0.0   1.0    2.0   13.00  233.0
AS          44.0    9.068182  21.667034  0.0   0.0    1.0    8.00  123.0
EU          45.0  142.222222  97.421738  0.0  59.0  128.0  195.00  370.0
OC          16.0   35.625000  64.555790  0.0   1.0    8.5   23.25  212.0
SA          12.0   62.416667  88.620189  1.0   3.0   12.0   98.50  221.0

In [15]:
# Step 6: Print the mean alcohol consumption per continent for every column
drinks.groupby("continent").mean(numeric_only=True)

,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
continent,,,,
AF,61.471698,16.339623,16.264151,3.007547
AS,37.045455,60.840909,9.068182,2.170455
EU,193.777778,132.555556,142.222222,8.617778
OC,89.687500,58.437500,35.625000,3.381250
SA,175.083333,114.750000,62.416667,6.308333

In [14]:
# Step 8: Print the mean, min and max values for spirit consumption.
drinks.groupby("continent")["spirit_servings"].agg(["mean", "min", "max"])

                 mean  min  max
continent
AF          16.339623    0  152
AS          60.840909    0  326
EU         132.555556    0  373
OC          58.437500    0  254
SA         114.750000   25  302