In [14]:
# Step 1: Import the libraries
import pandas as pd
from scipy.datasets import ascent

In [15]:
# Step 2 and 3
users = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user", sep="|")
users.head()

   user_id  age gender  occupation zip_code
0        1   24      M  technician    85711
1        2   53      F       other    94043
2        3   23      M      writer    32067
3        4   24      M  technician    43537
4        5   33      F       other    15213

In [16]:
users.shape

(943, 5)

In [17]:
# Step 4: Discover what is the mean age per occupation
round(users.groupby("occupation")["age"].mean())

occupation
administrator    39.0
artist           31.0
doctor           44.0
educator         42.0
engineer         36.0
entertainment    29.0
executive        39.0
healthcare       42.0
homemaker        33.0
lawyer           37.0
librarian        40.0
marketing        38.0
none             27.0
other            35.0
programmer       33.0
retired          63.0
salesman         36.0
scientist        36.0
student          22.0
technician       33.0
writer           36.0
Name: age, dtype: float64

In [18]:
users.head()

   user_id  age gender  occupation zip_code
0        1   24      M  technician    85711
1        2   53      F       other    94043
2        3   23      M      writer    32067
3        4   24      M  technician    43537
4        5   33      F       other    15213

In [32]:
# Step 5: Discover the Male ratio per occupation and sort it from the most to the least
grouped = users.groupby("occupation")

male_count = grouped["gender"].apply(lambda x: (x=="M").sum())
total_count = grouped["gender"].count()
male_ratio = (male_count/total_count)*100
male_ratio.sort_values(ascending=False)

occupation
doctor           100.000000
engineer          97.014925
technician        96.296296
retired           92.857143
programmer        90.909091
executive         90.625000
scientist         90.322581
entertainment     88.888889
lawyer            83.333333
salesman          75.000000
educator          72.631579
student           69.387755
other             65.714286
marketing         61.538462
writer            57.777778
none              55.555556
administrator     54.430380
artist            53.571429
librarian         43.137255
healthcare        31.250000
homemaker         14.285714
Name: gender, dtype: float64

In [26]:
# Step 6: For each occupation, calculate the minimum and maximum ages
users.groupby("occupation")["age"].agg(["min", "max"])

               min  max
occupation
administrator   21   70
artist          19   48
doctor          28   64
educator        23   63
engineer        22   70
entertainment   15   50
executive       22   69
healthcare      22   62
homemaker       20   50
lawyer          21   53
librarian       23   69
marketing       24   55
none            11   55
other           13   64
programmer      20   63
retired         51   73
salesman        18   66
scientist       23   55
student          7   42
technician      21   55
writer          18   60

In [31]:
# Step 7: For each combination of occupation and gender, calculate the mean age
round(users.groupby(["occupation", "gender"])["age"].agg(["mean"]), 1)

                      mean
occupation    gender
administrator F       40.6
              M       37.2
artist        F       30.3
              M       32.3
doctor        M       43.6
educator      F       39.1
              M       43.1
engineer      F       29.5
              M       36.6
entertainment F       31.0
              M       29.0
executive     F       44.0
              M       38.2
healthcare    F       39.8
              M       45.4
homemaker     F       34.2
              M       23.0
lawyer        F       39.5
              M       36.2
librarian     F       40.0
              M       40.0
marketing     F       37.2
              M       37.9
none          F       36.5
              M       18.6
other         F       35.5
              M       34.0
programmer    F       32.2
              M       33.2
retired       F       70.0
              M       62.5
salesman      F       27.0
              M       38.6
scientist     F       28.3
              M       36.3
student       F       20.8
              M       22.7
technician    F       38.0
              M       33.0
writer        F       37.6
              M       35.3