In [12]:
import numpy as np
import pandas as pd

In [13]:
baby_names = pd.read_csv("https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/US_Baby_Names/US_Baby_Names_right.csv")
baby_names.head()

   Unnamed: 0     Id     Name  Year Gender State  Count
0       11349  11350     Emma  2004      F    AK     62
1       11350  11351  Madison  2004      F    AK     48
2       11351  11352   Hannah  2004      F    AK     46
3       11352  11353    Grace  2004      F    AK     44
4       11353  11354    Emily  2004      F    AK     41

In [14]:
baby_names.shape

(1016395, 7)

In [15]:
# Step 5. Delete the column 'Unnamed: 0' and 'Id'
baby_names.drop(columns=["Unnamed: 0", "Id"], inplace=True)

In [22]:
baby_names.shape

(1016395, 5)

In [24]:
baby_names.sample(4)

            Name  Year Gender State  Count
794019    Amelia  2004      F    RI     22
681534    Jostin  2007      M    NY      5
947116  Zakariya  2004      M    VA      5
604657   Yamilet  2011      F    NJ     11

In [26]:
# Step 6. What year has the highest number of baby names in the dataset?
baby_names.groupby("Year")["Count"].sum().sort_values(ascending=False)

Year
2007    3412417
2006    3387737
2008    3340318
2005    3305315
2004    3293984
2009    3232116
2010    3116548
2014    3113611
2011    3079145
2012    3073858
2013    3066443
Name: Count, dtype: int64

In [28]:
# Step 7. Is there more male or female names in the dataset?
baby_names["Gender"].value_counts().sort_values(ascending=False)

Gender
F    558846
M    457549
Name: count, dtype: int64

In [44]:
# Step 8. Group the dataset by name and assign to names
names = baby_names.groupby("Name").sum()
names

,Year,Gender,State,Count
Name,,,,
Aaban,4027,MM,NYNY,12
Aadan,8039,MMMM,CACACATX,23
Aadarsh,2009,M,IL,5
Aaden,393963,MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM...,ALALALALALALALARARARAZAZAZAZAZAZCACACACACACACA...,3426
Aadhav,2014,M,CA,6
...,...,...,...,...
Zyra,14085,FFFFFFF,CACACAFLTXTXTX,42
Zyrah,4024,FF,CATX,11
Zyren,2013,M,TX,6
Zyria,20089,FFFFFFFFFF,GAGAGALALALATXTXTXTX,59
Zyriah,18087,FFFFFFFFF,GAGALATXTXTXTXTXTX,58

In [45]:
# Step 9. How many different names exist in the dataset?
baby_names["Name"].nunique()

17632

In [46]:
# Step 10. What is the name with most occurrences?
names["Count"].idxmax()

'Jacob'

In [47]:
# Step 11. How many different names have the least occurrences?
baby_names["Name"].value_counts().sort_values(ascending=True)

Name
Thaddaeus       1
Montanna        1
Anaka           1
Shouana         1
Luanna          1
             ...
Hayden       1049
Peyton       1064
Jordan       1073
Avery        1080
Riley        1112
Name: count, Length: 17632, dtype: int64