In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("play_tennis.csv")
df

    day   outlook  temp humidity    wind play
0    D1     Sunny   Hot     High    Weak   No
1    D2     Sunny   Hot     High  Strong   No
2    D3  Overcast   Hot     High    Weak  Yes
3    D4      Rain  Mild     High    Weak  Yes
4    D5      Rain  Cool   Normal    Weak  Yes
5    D6      Rain  Cool   Normal  Strong   No
6    D7  Overcast  Cool   Normal  Strong  Yes
7    D8     Sunny  Mild     High    Weak   No
8    D9     Sunny  Cool   Normal    Weak  Yes
9   D10      Rain  Mild   Normal    Weak  Yes
10  D11     Sunny  Mild   Normal  Strong  Yes
11  D12  Overcast  Mild     High  Strong  Yes
12  D13  Overcast   Hot   Normal    Weak  Yes
13  D14      Rain  Mild     High  Strong   No

In [3]:
df.shape

(14, 6)

## Calculating Probabilities for Independent Features

In [4]:
# P(Yes)
# P(No)

df["play"].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [5]:
prob_yes = 9/14
prob_no = 5/14

print(prob_yes)
print(prob_no)

0.6428571428571429
0.35714285714285715

In [6]:
# Outlook Column
pd.crosstab(df["outlook"], df["play"])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [7]:
prob_overcast_no = 0
prob_overcast_yes = 4/9
prob_rain_no = 2/5
prob_rain_yes = 3/9
prob_sunny_no = 3/5
prob_sunny_yes = 2/9

In [8]:
# Temp column
pd.crosstab(df["temp"], df["play"])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [9]:
prob_cool_no = 1/5
prob_cool_yes = 3/9
prob_hot_no = 2/5
prob_hot_yes = 2/9
prob_mild_no = 2/5
prob_mild_yes = 4/9

In [10]:
# Humidity Column
pd.crosstab(df["humidity"], df["play"])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [11]:
prob_high_no = 4/5
prob_high_yes = 3/9
prob_normal_no = 1/5
prob_normal_yes = 6/9

In [12]:
# Wind Column
pd.crosstab(df["wind"], df["play"])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [13]:
prob_strong_no = 3/5
prob_strong_yes =  3/9
prob_weak_no = 2/5
prob_weak_yes = 6/9

### Problem 1: Outlook=Sunny, Temp=Hot, humidity=high, wind=weak
Play or no play??

In [14]:
p_yes = prob_sunny_yes * prob_hot_yes * prob_high_yes * prob_weak_yes * prob_yes
p_no = prob_sunny_no * prob_hot_no * prob_high_no * prob_weak_no * prob_no

In [15]:
print(p_yes)
print(p_no)

0.007054673721340387
0.02742857142857143

In [16]:
## No Play because that prob is higher