# SelectKBest on a Custom Housing Dataset

In [1]:
# Import the libraries
import numpy as np
import pandas as pd
from sklearn.feature_selection import SelectKBest, f_regression
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

### Create a dataset

In [2]:
# Create a dataset
np.random.seed(42)
num_samples = 500

data = {
    "house_size": np.random.normal(2000, 500, num_samples),             # sqft
    "num_rooms": np.random.randint(3, 8, num_samples),                  # rooms
    "crime_rate": np.random.uniform(0, 1, num_samples),                 # 0 = safe, 1 = dangerous
    "distance_to_city_center": np.random.uniform(1, 30, num_samples),   # miles
    "school_rating": np.random.uniform(1, 10, num_samples),             # 1-10
    "age_of_house": np.random.randint(1, 80, num_samples),              # years
}

df = pd.DataFrame(data)
df.head()

,house_size,num_rooms,crime_rate,distance_to_city_center,school_rating,age_of_house
0,2248.357077,4,0.768273,23.635240,8.257633,60
1,1930.867849,4,0.417767,8.969375,5.133159,66
2,2323.844269,5,0.421357,24.855815,1.467609,66
3,2761.514928,5,0.737582,13.288409,8.076504,13
4,1882.923313,7,0.238777,20.358947,2.812274,56

In [3]:
# Create a target variable: House Price
df["price"] = (
    df["house_size"] * 150
    + df["school_rating"] * 4000
    - df["crime_rate"] * 30000
    - df["age_of_house"] * 500
    - df["distance_to_city_center"] * 1500
    + np.random.normal(0, 20000, num_samples)   # noise
)

In [4]:
df.head()

,house_size,num_rooms,crime_rate,distance_to_city_center,school_rating,age_of_house,price
0,2248.357077,4,0.768273,23.635240,8.257633,60,251425.554434
1,1930.867849,4,0.417767,8.969375,5.133159,66,244035.162978
2,2323.844269,5,0.421357,24.855815,1.467609,66,289330.307496
3,2761.514928,5,0.737582,13.288409,8.076504,13,409477.271649
4,1882.923313,7,0.238777,20.358947,2.812274,56,237999.172488

### Split the data

In [5]:
X = df.drop("price", axis=1)
y = df["price"]

### Apply SelectKBest

In [10]:
# Create a SelectKBest object.
# Use f-regression as the statistical test
# k=3 features, after scoring all features, keep only the 3 highest scoring ones. So selector is now a feature-selection model
selector = SelectKBest(score_func=f_regression, k=3)
selector

SelectKBest(k=3, score_func=<function f_regression at 0x000002732BE9C2C0>)

In [13]:
# It calculates the F-score for each variable in X, ranks all the features and then decides which 3 features to keep
# .transform(X) --> Creates a new dataset containing only those selected 3 features and removes all other non-selected features
X_new = selector.fit_transform(X, y)

In [14]:
# After I run fit or fit_transform, the selector knows which features were chosen. .get_support() returns a boolean mask indicating which features were selected
selected_features = X.columns[selector.get_support()]
selected_features

Index(['house_size', 'crime_rate', 'school_rating'], dtype='object')

In [8]:
print(f"Top Selected Features: {selected_features}")

Top Selected Features: Index(['house_size', 'crime_rate', 'school_rating'], dtype='object')